테라폼 변경

diff --git a/frontend/react-app/Dockerfile b/frontend/react-app/Dockerfile
--- a/frontend/react-app/Dockerfile
+++ b/frontend/react-app/Dockerfile
@@ -7,14 +7,11 @@ WORKDIR /app
 # 루트 디렉토리의 모든 파일을 복사합니다.
 COPY . .
 
-# Yarn Berry를 사용할 수 있도록 corepack을 활성화합니다.
+# Corepack을 활성화하여 프로젝트가 올바른 Yarn 버전을 사용하도록 합니다.
 RUN corepack enable
 
 # Yarn 버전을 프로젝트에 맞게 설정합니다.
 RUN corepack prepare yarn@4.4.1 --activate
-
-# Yarn 버전을 Berry로 설정합니다.
-RUN yarn set version berry
 
 # 의존성 설치 (루트 디렉토리)
 RUN yarn install || { echo "yarn install failed"; exit 1; }
@@ -62,6 +59,9 @@ RUN corepack enable
 # Yarn 버전을 프로젝트에 맞게 설정합니다.
 RUN corepack prepare yarn@4.4.1 --activate
 
+# Node.js 버전 및 Yarn 버전 확인
+RUN node --version && yarn --version
+
 # 루트 디렉토리의 모든 파일을 복사합니다.
 COPY --from=build /app .
 
@@ -69,7 +69,7 @@ COPY --from=build /app .
 ENV PATH /app/node_modules/.bin:$PATH
 
 # 최종 프로덕션 환경에서 의존성 재설치
-RUN yarn install || { echo "Final yarn install failed"; exit 1; }
+RUN yarn workspaces focus --production || { echo "Final yarn install failed"; exit 1; }
 
 WORKDIR /app/frontend/react-app
 
